language: python
python:
  - 3.6
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt
script: pytest
after_success:
  - zappa update dev
  - codecov
